// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.5
// source: provider/localSecp256k1/localSecp256k1.proto

package localSecp256k1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocalSecp256K1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type    string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Slot    string `protobuf:"bytes,3,opt,name=slot,proto3" json:"slot,omitempty"`
	PubKey  []byte `protobuf:"bytes,4,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	PrivKey []byte `protobuf:"bytes,5,opt,name=PrivKey,proto3" json:"PrivKey,omitempty"`
}

func (x *LocalSecp256K1) Reset() {
	*x = LocalSecp256K1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_provider_localSecp256k1_localSecp256k1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalSecp256K1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalSecp256K1) ProtoMessage() {}

func (x *LocalSecp256K1) ProtoReflect() protoreflect.Message {
	mi := &file_provider_localSecp256k1_localSecp256k1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalSecp256K1.ProtoReflect.Descriptor instead.
func (*LocalSecp256K1) Descriptor() ([]byte, []int) {
	return file_provider_localSecp256k1_localSecp256k1_proto_rawDescGZIP(), []int{0}
}

func (x *LocalSecp256K1) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LocalSecp256K1) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LocalSecp256K1) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *LocalSecp256K1) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *LocalSecp256K1) GetPrivKey() []byte {
	if x != nil {
		return x.PrivKey
	}
	return nil
}

var File_provider_localSecp256k1_localSecp256k1_proto protoreflect.FileDescriptor

var file_provider_localSecp256k1_localSecp256k1_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2f, 0x6c, 0x6f, 0x63, 0x61, 0x6c,
	0x53, 0x65, 0x63, 0x70, 0x32, 0x35, 0x36, 0x6b, 0x31, 0x2f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x53,
	0x65, 0x63, 0x70, 0x32, 0x35, 0x36, 0x6b, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c,
	0x69, 0x6d, 0x70, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x70, 0x32, 0x35, 0x36, 0x6b, 0x31, 0x22, 0x7e, 0x0a, 0x0e,
	0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x70, 0x32, 0x35, 0x36, 0x6b, 0x31, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x75,
	0x62, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x50, 0x75, 0x62, 0x4b,
	0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x72, 0x69, 0x76, 0x4b, 0x65, 0x79, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x50, 0x72, 0x69, 0x76, 0x4b, 0x65, 0x79, 0x42, 0x18, 0x5a, 0x16,
	0x2f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x53, 0x65, 0x63,
	0x70, 0x32, 0x35, 0x36, 0x6b, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_provider_localSecp256k1_localSecp256k1_proto_rawDescOnce sync.Once
	file_provider_localSecp256k1_localSecp256k1_proto_rawDescData = file_provider_localSecp256k1_localSecp256k1_proto_rawDesc
)

func file_provider_localSecp256k1_localSecp256k1_proto_rawDescGZIP() []byte {
	file_provider_localSecp256k1_localSecp256k1_proto_rawDescOnce.Do(func() {
		file_provider_localSecp256k1_localSecp256k1_proto_rawDescData = protoimpl.X.CompressGZIP(file_provider_localSecp256k1_localSecp256k1_proto_rawDescData)
	})
	return file_provider_localSecp256k1_localSecp256k1_proto_rawDescData
}

var file_provider_localSecp256k1_localSecp256k1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_provider_localSecp256k1_localSecp256k1_proto_goTypes = []interface{}{
	(*LocalSecp256K1)(nil), // 0: impl.provider.localSecp256k1.LocalSecp256k1
}
var file_provider_localSecp256k1_localSecp256k1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_provider_localSecp256k1_localSecp256k1_proto_init() }
func file_provider_localSecp256k1_localSecp256k1_proto_init() {
	if File_provider_localSecp256k1_localSecp256k1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_provider_localSecp256k1_localSecp256k1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalSecp256K1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_provider_localSecp256k1_localSecp256k1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_provider_localSecp256k1_localSecp256k1_proto_goTypes,
		DependencyIndexes: file_provider_localSecp256k1_localSecp256k1_proto_depIdxs,
		MessageInfos:      file_provider_localSecp256k1_localSecp256k1_proto_msgTypes,
	}.Build()
	File_provider_localSecp256k1_localSecp256k1_proto = out.File
	file_provider_localSecp256k1_localSecp256k1_proto_rawDesc = nil
	file_provider_localSecp256k1_localSecp256k1_proto_goTypes = nil
	file_provider_localSecp256k1_localSecp256k1_proto_depIdxs = nil
}
